name: Helm deploy

on:
  workflow_call:
    inputs:
      chartName:
        required: true
        type: string
      version:
        type: string
      env:
        required: true
        type: string
        default: 'dev'
      namespace:
        required: true
        type: string
      operation:
        required: true
        type: string
        default: 'upgrade'

env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  deploy:
    concurrency:
      group: ${{ inputs.chartName }}-${{ inputs.env }}
      cancel-in-progress: ${{ inputs.env != 'dev' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Registry Login
        id: login
        run: |
          echo ${{ secrets.GH_TOKEN }} | helm registry login ghcr.io --username ${{ github.repository_owner }} --password-stdin
      
      - name: Substitute Secrets
        uses: Lambdaspire/action-substitute-secrets-in-file@main
        with:
          file: values-${{ inputs.env }}.yaml
          tokenPattern: ${TOKEN}
          secretsJson: ${{ toJSON(secrets) }}

      - name: Create kubeconfig
        env:
          ENV: ${{ inputs.env }}
        run: |
            mkdir -p ~/.kube
            touch ~/.kube/config
            cat <<\EOT > ~/.kube/config
            ${{ secrets[format('{0}_KUBECONFIG', env.ENV)] }}
            EOT

      - name: Helm upgrade
        if: inputs.operation == 'upgrade'
        run: |
            helm upgrade --install --create-namespace --atomic --namespace ${{ inputs.namespace }} --version ${{ inputs.version }} --values values-${{ inputs.env }}.yaml ${{ inputs.chartName }} oci://ghcr.io/mars-office/${{ inputs.chartName }}
      
      - name: Helm uninstall
        if: inputs.operation == 'uninstall'
        run: |
            helm uninstall --namespace ${{ inputs.namespace }} ${{ inputs.chartName }}