name: Docker build and push

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      platforms:
        required: false
        type: string
        default: 'linux/amd64,linux/arm64'
      pushDisabled:
        required: false
        type: boolean
        default: false

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: ${{ inputs.pushDisabled == false && ((github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch')) }}
          context: .
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/mars-office/${{ github.event.repository.name }}:latest,ghcr.io/mars-office/${{ github.event.repository.name }}:${{ inputs.version }}
          build-args: |
            DEPLOYABLE_VERSION=${{ inputs.version }}
            GH_TOKEN=${{secrets.GH_TOKEN}}