name: Docker run

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      version:
        type: string
      env:
        required: true
        type: string
        default: 'dev'

jobs:
  docker_run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: test
        env:
          TEMPVARS: ${{ toJson(env) }}
        run: |
            echo $HUNA_URL
            echo "$TEMPVARS"

      # - name: Docker run
      #   run: |
      #       docker run --env-file=$GITHUB_ENV --name tempctr ghcr.io/mars-office/${{ inputs.imageName }}:v${{ inputs.version }}