name: Docker run

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      version:
        type: string
      env:
        required: true
        type: string
        default: 'dev'

jobs:
  docker_run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build envfile
        env:
          TEMPVARS: ${{ toJson(vars) }}
          TEMPENV: ${{ toJson(env) }}
        run: |
            echo "$(jq -r 'to_entries[] | [.key,.value] | join("=")' <<< $TEMPVARS)" > ./envfile
            echo "$(jq -r 'to_entries[] | [.key,.value] | join("=")' <<< $TEMPENV)" >> ./envfile
      
      - name: Ensure secrets.env
        run: touch secrets.env

      - name: Substitute Secrets
        uses: Lambdaspire/action-substitute-secrets-in-file@main
        with:
          file: secrets.env
          tokenPattern: ${TOKEN}
          secretsJson: ${{ toJSON(secrets) }}

      - name: Docker run
        run: |
            docker run --rm --env-file=./envfile --env-file=./secrets.env --name tempctr ghcr.io/mars-office/${{ inputs.imageName }}:v${{ inputs.version }}

      - name: Cleanup
        run: rm -rf ./envfile