name: Download kubeconfig

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  download_kubeconfig:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Output secret to temp file
        run: echo '${{ secrets[format('{0}_KUBECONFIG', inputs.env)] }}' > /tmp/kubeconfig_${{ inputs.env }}.yaml

      - name: Upload kubeconfig to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.env }}_kubeconfig
          path: /tmp/kubeconfig_${{ inputs.env }}.yaml