name: Helm Build and Push

on:
  workflow_call:
    inputs:
      helmVersion:
        required: false
        type: string
        default: '3.11.3'
      workingDirectory:
        required: false
        type: string
        default: '.'

env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  helm_build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '${{ inputs.helmVersion }}'
          token: ${{ secrets.GH_TOKEN }}
        id: install

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Chart Dependencies
        run: helm dependency update
        id: update
        working-directory: ${{ inputs.workingDirectory }}

      - name: Lint Chart
        run: helm lint ${{ inputs.workingDirectory }}
        id: lint

      - name: Dry Template Chart
        run: helm template ${{ inputs.workingDirectory }}
        id: template

      - name: Package Chart
        run: helm package ${{ inputs.workingDirectory }}
        id: package

      - name: Upload tar.gz Chart
        uses: actions/upload-artifact@v3
        with:
          name: chart
          path: ${{ inputs.workingDirectory }}/*.tar.gz