name: Helm Build and Push

on:
  workflow_call:
    inputs:
      helmVersion:
        required: false
        type: string
        default: '3.11.3'
      workingDirectory:
        required: false
        type: string
        default: '.'

env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  helm_build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '${{ inputs.helmVersion }}'
          token: ${{ secrets.GH_TOKEN }}
        id: install

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Chart Dependencies
        run: helm dependency update
        id: update
        working-directory: ${{ inputs.workingDirectory }}

      - name: Lint Chart
        run: helm lint ${{ inputs.workingDirectory }}
        id: lint

      - name: Dry Template Chart
        run: helm template ${{ inputs.workingDirectory }}
        id: template

      - name: Package Chart
        run: helm package ${{ inputs.workingDirectory }}
        id: package

      - name: Upload tar.gz Chart
        id: upload
        uses: actions/upload-artifact@v3
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch') }}
        with:
          name: chart
          path: ./*.tar.gz

  helm_push:
    runs-on: ubuntu-latest
    needs: [helm_build]
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch') }}
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '${{ inputs.helmVersion }}'
          token: ${{ secrets.GH_TOKEN }}
        id: install
     
      - name: Download tar.gz Chart
        id: download
        uses: actions/download-artifact@v3
        with:
          name: chart
          path: '.'