name: Helm Build and Push

on:
  workflow_call:
    inputs:
      helmVersion:
        required: false
        type: string
        default: '3.11.3'
      workingDirectory:
        required: false
        type: string
        default: '.'

env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  helm_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '${{ inputs.helmVersion }}'
          token: ${{ secrets.GH_TOKEN }}
        id: install

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Chart Dependencies
        run: helm dependency update
        id: update
        working-directory: ${{ inputs.workingDirectory }}

      - name: Lint Chart
        run: helm lint .
        working-directory: ${{ inputs.workingDirectory }}
        id: lint

      - name: Dry Template Chart
        run: helm template .
        working-directory: ${{ inputs.workingDirectory }}
        id: template

      - name: Package Chart
        run: helm package .
        id: package
        working-directory: ${{ inputs.workingDirectory }}
        
      - name: Registry Login
        id: login
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch') }}
        run: |
          echo ${{ secrets.GH_TOKEN }} | helm registry login ghcr.io --username ${{ github.repository_owner }} --password-stdin

      - name: Helm Push
        id: push
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch') }}
        run: |
          helm push ${{ inputs.workingDirectory }}/*.tgz oci://ghcr.io/${{ github.repository_owner }}