name: Helm Build and Push

on:
  workflow_call:
    inputs:
      helmVersion:
        required: false
        type: string
        default: '3.11.3'
      workingDirectory:
        required: false
        type: string
        default: '.'

jobs:
  helm_build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '${{ inputs.helmVersion }}'
          token: ${{ secrets.GH_TOKEN }}
        id: install