name: Snyk IaC TerraForm TFPlan

on:
  workflow_call:
    inputs:
      folder:
        type: string
        required: false
        default: '.'
        
jobs:
  snyk_iac_tfplan:
    permissions:
      contents: read
      security-events: write
      actions: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download tfplan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ${{inputs.folder}}/tfplan

      - name: Snyk scan TfPlan IaC
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --scan=resource-changes --severity-threshold=high --sarif-file-output=snyk.sarif
          file: ${{inputs.folder}}/tfplan

      - name: Upload Snyk report as sarif 📦
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif