name: Snyk IaC

on:
  workflow_call:
        
jobs:
  snyk_iac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Snyk scan IaC
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Upload Snyk report as sarif 📦
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif