name: TerraForm

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: choice
        options:
          - dev'
          - uat
          - prod
      tfVersion:
        required: false
        type: number
        default: 1.4.2
    secrets:
      terraformToken:
        required: true

jobs:
  tf_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tfVersion }}
          cli_config_credentials_token: ${{ secrets.terraformToken }}
      
      - name: Checkout
        uses: actions/checkout@v3
